CEFR_LEVELS = {
    "A1": {
        "level": "A1",
        "label": "Beginner / Elementary",
        "study_hours": "90-100",
        "source_name": "EnglishRadar",
        "source_url": "https://www.englishradar.com/english-levels/english-level-a1/",
        "can_do": [
            "understand and use familiar everyday expressions and very basic phrases",
            "introduce yourself and others",
            "ask and answer questions about personal details such as where you live, people you know, and things you have",
            "interact in a simple way when the other person speaks slowly and clearly",
        ],
        "communication_targets": [
            "Exchanging greetings",
            "Giving personal information",
            "Using numbers, days, months, years",
            "Asking for and telling the time",
            "Describing people",
            "Giving information about objects",
            "Describing places",
            "Describing habits and routines",
            "Expressing likes and dislikes",
            "Describing simple actions",
        ],
        "vocabulary_targets": [
            "Days of the week and months",
            "Numbers and prices",
            "Countries and nationalities",
            "Colours",
            "Personal possessions",
            "Parts of the body",
            "Family and friends",
            "Food and drinks",
            "Household rooms and objects",
            "Clothes",
        ],
        "grammar_targets": [
            "Question words",
            "Possessive adjectives and pronouns",
            "Present simple",
            "There is/There are",
            "Imperatives",
            "Present continuous (now or in progress)",
            "Prepositions of place",
            "Modals: can, can't, do, doesn't",
            "Simple adjectives",
            "Comparatives and superlatives",
        ],
    },
    "A2": {
        "level": "A2",
        "label": "Elementary / Pre-Intermediate",
        "study_hours": "180-200",
        "source_name": "EnglishRadar",
        "source_url": "https://www.englishradar.com/english-levels/english-level-a2/",
        "can_do": [
            "understand sentences and frequently used expressions related to common areas such as personal information, shopping, local geography, and employment",
            "communicate in simple and routine tasks requiring a direct exchange of information",
            "describe in simple terms aspects of your background and immediate matters",
        ],
        "communication_targets": [
            "Describing habits and daily routines",
            "Expressing ability and inability",
            "Describing past experiences",
            "Asking for and giving directions",
            "Describing personality and feelings",
            "Making comparisons",
            "Describing jobs",
            "Describing places",
            "Making requests (e.g. at a restaurant)",
            "Expressing future plans",
        ],
        "vocabulary_targets": [
            "Personality and feelings",
            "Food and drinks",
            "Education",
            "Jobs",
            "Weather",
            "Family and friends",
            "Daily routines",
            "Free-time activities",
            "Places in towns",
            "Body and health",
            "Transport and travel",
        ],
        "grammar_targets": [
            "Question words",
            "Adverbs of frequency",
            "Past simple",
            "Present continuous",
            "Present perfect simple",
            "Prepositions of time and place",
            "Comparatives and superlatives",
            "Like + ing",
            "Future simple: will",
            "Future: going to",
            "Past continuous",
        ],
    },
    "B1": {
        "level": "B1",
        "label": "Intermediate",
        "study_hours": "350-400",
        "source_name": "EnglishRadar",
        "source_url": "https://www.englishradar.com/english-levels/english-level-b1/",
        "can_do": [
            "understand the main points on familiar matters regularly encountered in work, school, and leisure",
            "deal with most situations likely to arise whilst travelling in an English-speaking area",
            "produce simple connected text on topics that are familiar or of personal interest",
            "describe experiences, events, dreams, hopes, ambitions, and briefly give reasons for opinions and plans",
        ],
        "communication_targets": [
            "Describing experiences and events",
            "Expressing hopes and ambitions",
            "Describing feelings",
            "Giving reasons",
            "Giving opinions",
            "Expressing preferences",
            "Stating obligations",
            "Expressing certainty",
            "Describing events in the past",
            "Describing events in the future",
        ],
        "vocabulary_targets": [
            "Feelings and emotions",
            "Travel and transport",
            "Entertainment",
            "Leisure activities",
            "Sport, health and fitness",
            "Education",
            "News and media",
            "Technology",
            "Time expressions for the past",
            "Time expressions for the future",
        ],
        "grammar_targets": [
            "Adverbs for time, degree, manner",
            "Past habits and states (used to)",
            "Present perfect simple",
            "Modals: should have, might have, etc.",
            "Present continuous (future)",
            "Future simple: will",
            "Future: going to",
            "Present perfect continuous",
            "Past continuous",
            "Past perfect simple",
            "Conditionals (first and second)",
            "Future continuous",
            "Passives",
        ],
    },
    "B2": {
        "level": "B2",
        "label": "Upper Intermediate",
        "study_hours": "500-600",
        "source_name": "EnglishRadar",
        "source_url": "https://www.englishradar.com/english-levels/english-level-b2/",
        "can_do": [
            "understand the main ideas of complex text on a variety of topics, including technical discussions in your field of specialisation",
            "interact with a degree of fluency and spontaneity that makes regular interaction with native speakers possible without strain",
            "produce clear, detailed text on a wide range of subjects and explain a viewpoint with advantages and disadvantages",
        ],
        "communication_targets": [
            "Describing experiences",
            "Expressing opinions",
            "Expressing agreement and disagreement",
            "Giving advice with advantages and disadvantages",
            "Making suggestions",
            "Expressing feelings and emotions",
            "Reporting events",
            "Speculating about events in past, present, future",
            "Adding emphasis",
            "Describing hopes and regrets",
        ],
        "vocabulary_targets": [
            "Work and education",
            "Lifestyles",
            "Money",
            "Crime and punishment",
            "Technology",
            "Media and communication",
            "Global issues",
            "Multi-word verbs",
            "Reporting verbs",
            "Linking expressions",
        ],
        "grammar_targets": [
            "Compound adjectives",
            "Adverbs for time, degree, manner",
            "Relative clauses",
            "Past perfect simple",
            "Past perfect continuous",
            "Present perfect continuous",
            "Passives",
            "Modals of speculation",
            "Conditionals (second and third)",
            "Mixed conditionals",
            "Reported speech",
            "Future perfect simple",
            "Future perfect continuous",
        ],
    },
    "C1": {
        "level": "C1",
        "label": "Advanced",
        "study_hours": "700-800",
        "source_name": "EnglishRadar",
        "source_url": "https://www.englishradar.com/english-levels/english-level-c1/",
        "can_do": [
            "understand a wide range of demanding, longer texts and recognise implicit meaning",
            "express yourself fluently and spontaneously without much obvious searching for expressions",
            "use language flexibly and effectively for social, academic, and professional purposes",
            "produce clear, well-structured, detailed text on complex subjects with controlled use of connectors and cohesive devices",
        ],
        "communication_targets": [
            "Expressing feelings and attitudes",
            "Emphasising an issue or a feeling",
            "Expressing opinions tentatively",
            "Developing an argument systematically",
            "Negotiating and conceding",
            "Describing cause and effect",
            "Expressing empathy and sympathy",
            "Expressing reservations",
            "Speculating about events in past, present, future",
            "Discussing complex subjects in detail",
        ],
        "vocabulary_targets": [
            "Life experiences and lifestyles",
            "Books and literature",
            "Money and business",
            "News and current affairs",
            "Global issues",
            "Technology",
            "Scientific developments",
            "Vague language",
            "Colloquial expressions",
            "Idiomatic expressions",
        ],
        "grammar_targets": [
            "Futures (revision)",
            "Passives (all forms)",
            "Compound adjectives and modifying gradable adjectives",
            "Adverbs and adverbial phrases: degree",
            "Modals in the past",
            "Mixed conditionals",
            "Ellipsis and substitution",
            "Adding emphasis - cleft sentences",
            "Adding emphasis - inversion with negative adverbials",
            "Multiword verbs",
        ],
    },
    "C2": {
        "level": "C2",
        "label": "Proficient",
        "study_hours": "1000-1200",
        "source_name": "EnglishRadar",
        "source_url": "https://www.englishradar.com/english-levels/english-level-c2/",
        "can_do": [
            "understand virtually everything heard or read with ease",
            "summarise information from different spoken and written sources, reconstructing arguments and accounts in a coherent presentation",
            "express yourself spontaneously, very fluently, and precisely, differentiating finer shades of meaning in complex situations",
        ],
        "communication_targets": [
            "Express yourself fluently and precisely in any topic",
            "Communicate accurately in formal and informal complex situations",
        ],
        "vocabulary_targets": [
            "Excellent range of vocabulary, including idiomatic expressions and colloquial language",
            "Use phrases and expressions accurately with natural and sophisticated control",
        ],
        "grammar_targets": [
            "Use a full range of grammatical structures accurately and appropriately",
            "Use different linguistic forms naturally to convey finer shades of meaning",
        ],
    },
}
